import { Montserrat } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/sidebar';
import Navbar from '@/components/navbar';
import { AuthProvider } from '@/context/AuthContext';

const montserrat = Montserrat({
  weight: '500',
  style: 'normal',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
