import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Montserrat({
    weight: "500",
    style: "normal",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="drawer lg:drawer-open">
                    <input
                        id="my-drawer-2"
                        type="checkbox"
                        className="drawer-toggle"
                    />
                    <div className="drawer-content flex flex-col items-center justify-center">
                        {children}
                    </div>
                    <div className="drawer-side">
                        <label
                            htmlFor="my-drawer-2"
                            aria-label="close sidebar"
                            className="drawer-overlay"
                        ></label>
                        <Sidebar />
                    </div>
                </div>
            </body>
        </html>
    );
}
